.\"EMACS: -*- nroff -*-

.TH SUPL-CERT 1 "version 1.0"
.SH NAME
supl-cert \- utility to create SSL keys and certificates for supl-proxy
.SH SYNOPISIS
.B supl-cert
[\fIdoman-name\fP]
.br
.SH DESCRIPTION
\fBsupl-cert\fP takes as the only parameter the domain name of the
server where the supl-proxy will be ran and what is set to client
(e.g. mobile phone) as the SUPL server.

.SH OPTIONS
The \fIdomain-name\fP of the supl-proxy machine.
.SH NOTES
.B *** DO NOT USE THESE KEYS FOR ANYTHING REQUIRING REAL SECURITY ***
.br

\fBsupl-proxy\fP expects to see these certificate and key files with
these names in the current working directory.

The CA certificate \fIca-cert.pem\fP file must be given to the SUPL
client device (e.g. mobile phone).
.SH FILES
.TP
.I ca-cert.pem
CA certificate. Copy over to the SUPL client device.
.TP
.I ca-priv.pem
CA private key. This file is not really needed.
.TP
.I srv-cert.pem
supl-proxy server certificate, signed by the CA certificate.
.TP
.I srv-priv.pem
supl-proxy server private key.
.SH BUGS
Please send any comments or bug reports to \fBtatu -at- tajuma.com\fP.
.SH HOMEPAGE
http://www.tajuma.com/supl
.SH AUTHOR
Tatu Männistö <tatu -at- tajuma.com>
