# Generated by ./configure script - Thu Oct 27 21:56:38 EEST 2011
# Modifications to this file are lost if ./configure is ran again.

CONF_VERSION = 1.0.5
CONF_CFLAGS = -Wall -O2 
CONF_ASN_CFLAGS = 
CONF_PREFIX = /usr
CONF_PRECOMPILED_ASN = yes
CONF_SUPL_DEBUG = 
CONF_ASN1_SKELETONS = 
